import Nav from "./(components)/Nav";
import Footer from "./Header-Footer/footer";
import AuthProvider from "./(components)/AuthProvider";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>
        <AuthProvider>
          <div className="m-2">{children}</div>
        </AuthProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
