import Nav from "./(components)/Nav";
import Footer from "./Header-Footer/footer";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>

        <div className="m-2">{children}</div>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
